<template>
  <div>
    <group :first="true">
      <ele>
        <div>
          <h3>v3.3.10</h3>
          <ul>
            <li>出借人奖励规则变更</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.3.9</h3>
          <ul>
            <li>详版信用报告加入手机号分析</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.3.8</h3>
          <ul>
            <li>加入裸条举报功能</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.3.7</h3>
          <ul>
            <li>加入版本介绍功能</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.3.4</h3>
          <ul>
            <li>变更出借默认时长</li>
            <li>运营商授信过程，第二次输入验证码前自动清空</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.3.3</h3>
          <ul>
            <li>用户浏览器错误统计更新</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.3.2</h3>
          <ul>
            <li>信用报告内加入借出记录风险提示</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.3.1</h3>
          <ul>
            <li>创建求借款成功后可直接分享</li>
            <li>信用报告内电话可直接拨打</li>
            <li>出借新添加两个档位</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.3.0</h3>
          <ul>
            <li>信用报告升级，借入借出记录更清晰</li>
            <li>加入常用手机号分析</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.17</h3>
          <ul>
            <li>提现成功后清除已输入的金额</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.14</h3>
          <ul>
            <li>提现是校验必须选择一张可用银行卡</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.13</h3>
          <ul>
            <li>确认借条时，提醒用户剩余借款额度</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.12</h3>
          <ul>
            <li>创建求借款和补借条时，提醒用户剩余借款额度</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.11</h3>
          <ul>
            <li>去掉首页的图片预加载，加速访问，节省带宽</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.10</h3>
          <ul>
            <li>变更 D+0 提示的文案</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.9</h3>
          <ul>
            <li>优化更新信用报告流程</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.8</h3>
          <ul>
            <li>资金状态加入【银行处理中】状态</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.7</h3>
          <ul>
            <li>常见问题补充 D+0 的手续费计算方法</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.4</h3>
          <ul>
            <li>提供 D+0 的功能</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.3</h3>
          <ul>
            <li>修改创建出借是默认的还款方式</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.2.0</h3>
          <ul>
            <li>出借人逾期以后，借款人可以看到出借人的紧急联系人联系方式</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.1.11</h3>
          <ul>
            <li>加入浏览器错误统计功能</li>
            <li>诉讼材料加入线上支付凭证下载功能</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.1.10</h3>
          <ul>
            <li>补充常见问题</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.1.9</h3>
          <ul>
            <li>变更部分提示文案</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.1.8</h3>
          <ul>
            <li>完善信用报告更新的流程</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.1.7</h3>
          <ul>
            <li>时间选择插件加入真实性校验功能</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.1.5</h3>
          <ul>
            <li>完善信用报告更新的流程</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.1.3</h3>
          <ul>
            <li>信用认证费用支付失败情况下可重新支付</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.1.0</h3>
          <ul>
            <li>下载证据功能完善，自动填充必要信息</li>
          </ul>
        </div>
      </ele>
      <ele>
        <div>
          <h3>v3.0.0</h3>
          <ul>
            <li>今借到 3.0 版本正式上线</li>
          </ul>
        </div>
      </ele>
    </group>
  </div>
</template>

<script type="text/ecmascript-6">
  export default{
    vuex: {
      getters: {},
      actions: {}
    },
    data () {
      return {}
    },
    components: {},
    computed: {},
    methods: {},
    route: {},
    created () {
    },
    attached () {
    }
  }
</script>

<style rel="stylesheet/scss"
       lang="scss"
       scoped>
</style>
